return {
	[1] = {
		name = "B1",
		icon = "http://www.roblox.com/asset/?id=125602614059845",
		description = "B1 description",
	},
	[2] = {
		name = "B2",
		icon = "http://www.roblox.com/asset/?id=82254019997610",
		description = "B2 description",
	},
	[3] = {
		name = "B3",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "B3 description",
	},
	[4] = {
		name = "B4",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "B4 description",
	},
}
