--!strict
return {
	[1] = {
		name = "B1",
		icon = "http://www.roblox.com/asset/?id=125602614059845",
		description = "B1 description",
		recipe = {
			{ materialId = 1, quantity = 10 },
			{ materialId = 2, quantity = 5 },
		},
		maxLevel = 5,
	},
	[2] = {
		name = "B2",
		icon = "http://www.roblox.com/asset/?id=82254019997610",
		description = "B2 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
		},
		maxLevel = 5,
	},
	[3] = {
		name = "B3",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "B3 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
			{ materialId = 3, quantity = 7 },
			{ materialId = 3, quantity = 11 },
			{ materialId = 3, quantity = 13 },
			{ materialId = 3, quantity = 145 },
		},
		maxLevel = 5,
	},
	[4] = {
		name = "B4",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "B4 description",
		recipe = {
			{ materialId = 1, quantity = 99 },
			{ materialId = 2, quantity = 99 },
			{ materialId = 3, quantity = 99 },
		},
		maxLevel = 5,
	},
}
