--!strict
return {
	[1] = {
		name = "Iron Scrap",
		icon = "http://www.roblox.com/asset/?id=125602614059845",
		rarity = 40,
		description = "It's a scrappy scrap scrap scrap scrappy scrap",
	},
	[2] = {
		name = "Crystal Shard",
		icon = "http://www.roblox.com/asset/?id=82254019997610",
		rarity = 300,
		description = "It's a shardy shard shard shard shardy shard",
	},
	[3] = {
		name = "Twig",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		rarity = 3,
		description = "It's a twiggy twig twig twig twiggy twig",
	},
}
