--!strict
return {
	[1] = {
		name = "C1",
		icon = "http://www.roblox.com/asset/?id=125602614059845",
		description = "A1 description",
	},
	[2] = {
		name = "C2",
		icon = "http://www.roblox.com/asset/?id=82254019997610",
		description = "A2 description",
	},
	[3] = {
		name = "C3",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "A3 description",
	},
	[4] = {
		name = "C4",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "A4 description",
	},
}
