--!strict
return {
	[1] = {
		name = "C1",
		icon = "http://www.roblox.com/asset/?id=125602614059845",
		description = "C1 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
	[2] = {
		name = "C2",
		icon = "http://www.roblox.com/asset/?id=82254019997610",
		description = "C2 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
	[3] = {
		name = "C3",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "C3 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
	[4] = {
		name = "C4",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "C4 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
}
