--!strict
return {
	[1] = {
		name = "A1",
		icon = "http://www.roblox.com/asset/?id=125602614059845",
		description = "A1 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
	[2] = {
		name = "A2",
		icon = "http://www.roblox.com/asset/?id=82254019997610",
		description = "A2 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
	[3] = {
		name = "A3",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "A3 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
	[4] = {
		name = "A4",
		icon = "http://www.roblox.com/asset/?id=113768270768853",
		description = "A4 description",
		recipe = {
			{ materialId = 1, quantity = 3 },
			{ materialId = 2, quantity = 4 },
			{ materialId = 3, quantity = 5 },
		},
		maxLevel = 5,
	},
}
