name: Deploy to Staging

on:
  push:
    branches:
    - development

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if Environment.luau contains "Dev"
        id: check_file
        run: |
          # Check if "Dev" is present in the file
          if grep -q "Dev" src/server/Environment.luau; then
            echo "File contains 'Dev'"
            echo "skip=false" >> $GITHUB_ENV
          else
            echo "File does not contain 'Dev'"
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Fail deployment if "Dev" is not present
        if: env.skip == 'true'
        run: |
          echo "Deployment skipped because 'Dev' is not present in Environment.luau"
          exit 1  # Exit with an error code to fail the job

      - name: Setup Aftman
        if: env.skip == 'false'
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Build and Deploy
        if: env.skip == 'false'
        run: |
          rojo build -o "RNG Battles.rbxl"
          rbxcloud experience publish -f "RNG Battles.rbxl" -p 18986008463 -u 6432287837 -t published -a ${{secrets.API_KEY}}